### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by ClearlyElevated** [siketyan/stateless-discord-bot#1]
What does stateless mean exactly? And it is powered by cloud flare workers rather then a traditional hosting provider or local system? In other words cloud flare is the hosting provider? Is the bot just offline until a command is ran or is it always on?

**Comment by siketyan** [comment]
> What does stateless mean exactly?

As a classic Discord Bot, we need to keep the connection to the Gateway API, during to be online to get any events.
However, in this example, it is possible to be online without the connection, using Slash Command feature.
So I call it "stateless", because the bot does not need to have their "state", including the connection and so on.

> And it is powered by cloud flare workers rather then a traditional hosting provider or local system? In other words cloud flare is the hosting provider?

This example is designed to use Cloudflare Workers to run the program.
Why I used it, is Cloudflare Workers is a "serverless" service, we only need to manage the code, without thinking servers.
Of course any FaaS (Function as a Service) services can be used.
Just an example.

> Is the bot just offline until a command is ran or is it always on?

Discord shows the bot is online whenever, as their status.
But the bot is actually offline, until any command is invoked.
Discord calls the bot using HTTP, so we only have to listen, without any connection at this time.
It is also a reason why I call this example stateless.
With this feature, the bot can be much scalable rather than classical bots.

**Comment by siketyan** [comment]
@ClearlyElevated Are your questions solved?
If no more question found, please close this issue.

**Comment by siketyan** [comment]
Closing issue due to no response yet. Feel free to re-open whenever if you had new questions!
